'use client';

import { Filter, MousePointer, Search, ChevronRight } from 'lucide-react';

import { StatusCard } from './shared';

export function BacklogSection() {
  return (
    <div className="space-y-6">
      <div className="space-y-4">
        <h4 className="font-semibold text-white">Backlog Dashboard</h4>
        <p className="text-gray-400">
          The backlog dashboard is your central hub for managing all improvement
          suggestions generated by PM Review.
        </p>
      </div>

      <div className="space-y-4">
        <h4 className="font-semibold text-white">Status Tabs</h4>
        <div className="grid gap-3 md:grid-cols-2">
          <StatusCard
            status="New"
            description="Newly created items awaiting review"
            color="text-blue-400"
          />
          <StatusCard
            status="Approved"
            description="Items approved for implementation"
            color="text-green-400"
          />
          <StatusCard
            status="In Progress"
            description="Items currently being implemented"
            color="text-yellow-400"
          />
          <StatusCard
            status="Completed"
            description="Successfully implemented items"
            color="text-gray-400"
          />
          <StatusCard
            status="Deferred"
            description="Items postponed for later"
            color="text-orange-400"
          />
          <StatusCard
            status="Rejected"
            description="Items that won't be implemented"
            color="text-red-400"
          />
        </div>
      </div>

      <div className="space-y-4">
        <h4 className="flex items-center gap-2 font-semibold text-white">
          <Filter className="h-5 w-5 text-gold" />
          Filtering Items
        </h4>
        <div className="rounded-lg border border-gray-700 bg-black/30 p-4">
          <ul className="space-y-2 text-sm text-gray-300">
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>
                <strong>Area:</strong> Frontend or Backend
              </span>
            </li>
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>
                <strong>Type:</strong> Dashboard, Discovery, Auth, Backend
              </span>
            </li>
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>
                <strong>Complexity:</strong> 1 (Trivial) to 5 (Very High)
              </span>
            </li>
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>
                <strong>Effort:</strong> Score range (e.g., 1-3 for quick wins)
              </span>
            </li>
          </ul>
        </div>
      </div>

      <div className="space-y-4">
        <h4 className="flex items-center gap-2 font-semibold text-white">
          <MousePointer className="h-5 w-5 text-gold" />
          Item Actions
        </h4>
        <div className="rounded-lg border border-gray-700 bg-black/30 p-4">
          <ul className="space-y-2 text-sm text-gray-300">
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>Click any row to view item details</span>
            </li>
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>Use checkboxes for bulk selection</span>
            </li>
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>Bulk approve, reject, or defer selected items</span>
            </li>
            <li className="flex items-center gap-2">
              <ChevronRight className="h-4 w-4 text-gold" />
              <span>Sort by any column header</span>
            </li>
          </ul>
        </div>
      </div>

      <div className="space-y-4">
        <h4 className="flex items-center gap-2 font-semibold text-white">
          <Search className="h-5 w-5 text-gold" />
          Quick Wins
        </h4>
        <p className="text-gray-400">
          Items with high impact and low effort are marked with a "Quick Win"
          badge. These are the best candidates for immediate implementation.
        </p>
      </div>
    </div>
  );
}
