'use client';

import { ContentCard } from './shared';

export function PRDSection() {
  return (
    <div className="space-y-6">
      <div className="space-y-4">
        <h4 className="font-semibold text-white">
          Product Requirements Documents
        </h4>
        <p className="text-gray-400">
          PRDs are detailed implementation plans generated by AI for each
          improvement item. They provide structured guidance for developers.
        </p>
      </div>

      <div className="space-y-4">
        <h4 className="font-semibold text-white">Generating a PRD</h4>
        <div className="rounded-lg border border-gray-700 bg-black/30 p-4">
          <ol className="space-y-3 text-sm text-gray-300">
            <li className="flex items-start gap-2">
              <span className="font-medium text-gold">1.</span>
              <span>Click on any item to open the detail modal</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-medium text-gold">2.</span>
              <span>
                Click the "Generate PRD" button (or press{' '}
                <kbd className="rounded bg-black px-1">G</kbd>)
              </span>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-medium text-gold">3.</span>
              <span>Wait for AI to generate the document</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="font-medium text-gold">4.</span>
              <span>View the PRD in the "PRD" tab</span>
            </li>
          </ol>
        </div>
      </div>

      <div className="space-y-4">
        <h4 className="font-semibold text-white">PRD Contents</h4>
        <div className="grid gap-3 md:grid-cols-2">
          <ContentCard
            title="Problem Statement"
            description="Clear description of the issue being addressed"
          />
          <ContentCard
            title="Proposed Solution"
            description="Detailed technical approach and implementation"
          />
          <ContentCard
            title="Success Criteria"
            description="Measurable goals for the implementation"
          />
          <ContentCard
            title="Technical Approach"
            description="Wave-based task breakdown for parallel execution"
          />
          <ContentCard
            title="Risks & Mitigations"
            description="Potential issues and how to address them"
          />
          <ContentCard
            title="Out of Scope"
            description="What is explicitly not included"
          />
        </div>
      </div>

      <div className="rounded-lg border border-yellow-800/30 bg-yellow-900/10 p-4">
        <p className="text-sm text-yellow-200/80">
          <strong>Note:</strong> PRDs are generated during the /pm-review
          command in Claude Code. Each backlog item includes a PRD when
          submitted.
        </p>
      </div>
    </div>
  );
}
