'use client';

import { DocsLayout } from '@/components/docs';

export default function ItemsPage() {
  return (
    <DocsLayout
      title="Item Details"
      description="Understanding the item detail modal and its views."
    >
      <h2>Opening Item Details</h2>
      <p>
        Click on any item row to open the detail modal. This shows comprehensive
        information about the improvement.
      </p>

      <h2>View Modes</h2>
      <p>The detail modal has multiple tabs:</p>

      <h3>Summary</h3>
      <p>Quick overview including:</p>
      <ul>
        <li>
          <strong>Problem</strong> - What issue this addresses
        </li>
        <li>
          <strong>Solution</strong> - Proposed fix
        </li>
        <li>
          <strong>Scores</strong> - Impact, effort, priority
        </li>
        <li>
          <strong>Category</strong> - Item type
        </li>
        <li>
          <strong>Status</strong> - Current state
        </li>
      </ul>

      <h3>PRD (Product Requirements Document)</h3>
      <p>Detailed documentation including:</p>
      <ul>
        <li>
          <strong>Overview</strong> - Problem statement and goals
        </li>
        <li>
          <strong>User Stories</strong> - Who benefits and how
        </li>
        <li>
          <strong>Requirements</strong> - What needs to be built
        </li>
        <li>
          <strong>Technical Approach</strong> - Implementation strategy
        </li>
        <li>
          <strong>Task Breakdown</strong> - Wave-based implementation plan
        </li>
        <li>
          <strong>Success Criteria</strong> - How to verify completion
        </li>
        <li>
          <strong>Out of Scope</strong> - What this doesn&apos;t include
        </li>
      </ul>

      <h3>Risk Analysis</h3>
      <p>6-factor risk assessment:</p>
      <ul>
        <li>
          <strong>Technical Risk</strong> - Implementation complexity
        </li>
        <li>
          <strong>Integration Risk</strong> - Impact on existing code
        </li>
        <li>
          <strong>Performance Risk</strong> - Potential slowdowns
        </li>
        <li>
          <strong>Security Risk</strong> - New vulnerabilities
        </li>
        <li>
          <strong>Scope Risk</strong> - Scope creep potential
        </li>
        <li>
          <strong>Testing Risk</strong> - QA difficulty
        </li>
      </ul>
      <p>Each factor is scored 1-10 with explanation.</p>

      <h3>Benefits</h3>
      <p>5-category benefit breakdown:</p>
      <ul>
        <li>
          <strong>User Experience</strong> - End-user benefit
        </li>
        <li>
          <strong>Sales Team</strong> - Business value
        </li>
        <li>
          <strong>Operations</strong> - Support/ops benefit
        </li>
        <li>
          <strong>Performance</strong> - Technical performance impact
        </li>
        <li>
          <strong>Reliability</strong> - System stability improvement
        </li>
      </ul>

      <h3>Timeline</h3>
      <p>History of the item:</p>
      <ul>
        <li>Created date</li>
        <li>Approval date (if approved)</li>
        <li>Execution start (if executed)</li>
        <li>Completion date (if completed)</li>
      </ul>

      <h2>Editing Items</h2>
      <p>Some fields can be edited:</p>
      <ul>
        <li>
          <strong>Title</strong> - Click to edit
        </li>
        <li>
          <strong>Problem</strong> - Click to edit
        </li>
        <li>
          <strong>Solution</strong> - Click to edit
        </li>
        <li>
          <strong>Status</strong> - Use action buttons
        </li>
      </ul>
      <p>
        Scores and PRDs are generated by Mason and cannot be manually edited.
      </p>

      <h2>Actions from Detail View</h2>
      <ul>
        <li>
          <strong>Approve</strong> - Mark ready for execution
        </li>
        <li>
          <strong>Reject</strong> - Decline this item
        </li>
        <li>
          <strong>Delete</strong> - Remove permanently
        </li>
        <li>
          <strong>Restore</strong> - Un-reject an item
        </li>
        <li>
          <strong>Regenerate PRD</strong> - Request new PRD generation
        </li>
      </ul>

      <h2>Keyboard Shortcuts</h2>
      <p>When the modal is open:</p>
      <ul>
        <li>
          <code>Esc</code> - Close modal
        </li>
        <li>
          <code>←</code> / <code>→</code> - Navigate between tabs
        </li>
      </ul>
    </DocsLayout>
  );
}
